### ISSUE TITLE
HCAEnc_lite

### ISSUE THREAD

**Issue by DuIslingr** [hozuki/DereTore#2]
Can I just use the one from the CriWare SDK? I have that so I mean I don't really want to go through the effort just to obtain the one from link provided lol. If you want me to send you a copy of it I can to be sure its compatible. In fact I have 2 variants. hcaenc.dll and hcaenc_lite.dll if you want to look at both.

**Comment by hozuki** [comment]
Sure you can.

`DereTore.Application.Encoder` is designed for `hcaenc_lite.dll` because the lite version is free to obtain despite the regional limitation. And, I don't have the pro version. Lucky you! \_(:з」∠)\_
The program itself is very simple, just a P/Invoke call. I think it will be easy to migrate to `hcaenc.dll` if you know the API. On the other hand, its pairing application `CipherConverter` is merely an encryption conversion program. Even you use the HCA encoded by `hcaenc.dll` as input, it still works when given the right arguments.

**Conslusion**: `hcaenc.dll` = `hcaenc_lite.dll` + `CipherConverter`. No matter which way you choose, the results are the same.

**Comment by DuIslingr** [comment]
Well both are attainable for free for any region really. The CriWare SDK is free to obtain for an evaluation period by simply submitting a request on their website. It's how I got mine. Did take a couple days to receive an email back however containing the login to access the sdk and my license files. The license doesn't even apply to the files mentioned. Only enforced on the .exes which to be honest is easily bypassible, but that's besides the point. So yeah. Thanks for the reply.

**Comment by hozuki** [comment]
You're welcome. Hope you like this toolkit. :smile:
